languaje: node_js

git:
  depth: 2

branches:
  except:
  - legacy
  - experimental

branches:
  only:
  - main

before_install:
  - python

install:
  - yarn install

script: 
  - yarn deploy
  - yarn test

before_script:
  - yarn test
after_script:
  - yarn clean

cache:
  directories:
    - node_modules

